"""Añadir campos oficio, fecha_recibido, juzgado, departamento a expedientes

Revision ID: 258441b908ab
Revises: 61e56793c16e
Create Date: 2025-05-07 16:07:57.192716

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '258441b908ab'
down_revision: Union[str, None] = '61e56793c16e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expedientes', sa.Column('oficio', sa.String(), nullable=True, comment='Número de oficio (ej. 250/2025)'))
    op.add_column('expedientes', sa.Column('fecha_recibido', sa.Date(), nullable=True, comment='Fecha en que se recibió el oficio'))
    op.add_column('expedientes', sa.Column('juzgado', sa.String(), nullable=True, comment='Nombre del Juzgado emisor'))
    op.add_column('expedientes', sa.Column('departamento', sa.String(), nullable=True, comment='Departamento del Juzgado emisor'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expedientes', 'departamento')
    op.drop_column('expedientes', 'juzgado')
    op.drop_column('expedientes', 'fecha_recibido')
    op.drop_column('expedientes', 'oficio')
    # ### end Alembic commands ###
