"""Crear tabla expedientes

Revision ID: 61e56793c16e
Revises:
Create Date: 2025-05-04 09:02:52.855362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61e56793c16e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - CORREGIDO ###

    # --- MANTENER: Crear tabla expedientes y sus índices ---
    op.create_table('expedientes',
        sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único del expediente'),
        sa.Column('expediente_nro', sa.String(), nullable=False, comment='Número o identificador del expediente (ej. IUE)'),
        sa.Column('usuario_id', sa.Integer(), nullable=True, comment='ID del usuario asociado (opcional por ahora)'),
        sa.Column('trabajado', sa.Boolean(), nullable=False, comment='Indica si el expediente ha sido trabajado (True) o no (False)'),
        sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora de creación del registro (automática)'),
        sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora de la última actualización (automática en updates)'),
        sa.PrimaryKeyConstraint('id', name=op.f('pk_expedientes'))
    )
    op.create_index(op.f('ix_expedientes_expediente_nro'), 'expedientes', ['expediente_nro'], unique=False)
    op.create_index(op.f('ix_expedientes_id'), 'expedientes', ['id'], unique=False)
    op.create_index(op.f('ix_expedientes_usuario_id'), 'expedientes', ['usuario_id'], unique=False)
    # --- FIN MANTENER ---

    # --- ELIMINADO: No borrar tablas preexistentes ---
    # op.drop_table('roles')
    # op.drop_table('users')
    # op.drop_table('departments')
    # --- FIN ELIMINADO ---

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - CORREGIDO ###

    # --- ELIMINADO: No recrear tablas preexistentes en downgrade ---
    # op.create_table('departments', ...)
    # op.create_table('users', ...)
    # op.create_table('roles', ...)
    # --- FIN ELIMINADO ---

    # --- MANTENER: Borrar tabla expedientes y sus índices en downgrade ---
    op.drop_index(op.f('ix_expedientes_usuario_id'), table_name='expedientes')
    op.drop_index(op.f('ix_expedientes_id'), table_name='expedientes')
    op.drop_index(op.f('ix_expedientes_expediente_nro'), table_name='expedientes')
    op.drop_table('expedientes')
    # --- FIN MANTENER ---

    # ### end Alembic commands ###
