"""Crear tabla access_logs

Revision ID: 730947d89a26
Revises: 258441b908ab
Create Date: 2025-05-25 10:28:51.466587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '730947d89a26'
down_revision: Union[str, None] = '258441b908ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('access_logs',
    sa.Column('id', sa.Integer(), nullable=False, comment='Identificador único del registro de acceso'),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Fecha y hora del evento'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Dirección IP del cliente que generó el evento'),
    sa.Column('action_description', sa.String(), nullable=False, comment='Descripción de la acción o evento registrado'),
    sa.Column('user_identifier', sa.String(), nullable=True, comment='Identificador del usuario (si está disponible)'),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Detalles adicionales sobre el evento en formato JSON'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_access_logs'))
    )
    op.create_index(op.f('ix_access_logs_action_description'), 'access_logs', ['action_description'], unique=False)
    op.create_index(op.f('ix_access_logs_id'), 'access_logs', ['id'], unique=False)
    op.create_index(op.f('ix_access_logs_timestamp'), 'access_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_access_logs_user_identifier'), 'access_logs', ['user_identifier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_access_logs_user_identifier'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_timestamp'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_id'), table_name='access_logs')
    op.drop_index(op.f('ix_access_logs_action_description'), table_name='access_logs')
    op.drop_table('access_logs')
    # ### end Alembic commands ###
